#!/usr/bin/env python

from nymms.utils import aws_helper, cli

parser = cli.NymmsDaemonCommand()
args = parser.parse_args()

cli.setup_logging(args.verbose)

from nymms.config import config
from nymms.keeper.state_keeper import StateKeeper

config.load_config(args.config)

region = config.settings['queue_region']
conn_mgr = aws_helper.ConnectionManager(region)

keeper = StateKeeper(conn_mgr)
keeper.run()
