#!/usr/bin/env python

import os
from boto import sqs, sns, sdb

from nymms.utils import logutil, aws_helper

logger = logutil.setup_root_logger(stdout=logutil.INFO,
        filename='/tmp/nymms-keeper-%d.log' % (os.getpid()),
        file_level=logutil.DEBUG)
logutil.quiet_boto_logging()

from nymms.config import config
config.load_config('~/git/nymms/conf/config.yaml')

from nymms.keeper.state_keeper import StateKeeper

region = config.settings['queue_region']
conn_mgr = aws_helper.ConnectionManager(region)

keeper = StateKeeper(conn_mgr)
keeper.run()
