#!/usr/bin/env python
""" Command line script to launch the NYMMS REST API. """

import importlib

from nymms.config import config
from nymms.utils import cli

parser = cli.NymmsCommandArgs(__doc__)
args = parser.parse_args()
logger = cli.setup_logging(args.verbose)

config.load_config(args.config)

from nymms.api import routes

for plugin in config.settings.get('api', []).get('plugins', []):
    importlib.import_module(plugin)

routes.nymms_api.run(debug=True)
