#!/usr/bin/env python

from nymms.utils import aws_helper, cli

parser = cli.NymmsDaemonCommand()
args = parser.parse_args()

cli.setup_logging(args.verbose)

from nymms.config import config
from nymms.reactor.sqs_reactor import SQSReactor
from nymms.alerter.ses_alerter import SESAlerter

config.load_config(args.config)

alerter = SESAlerter(config.settings['queue_region'])

region = config.settings['queue_region']
conn_mgr = aws_helper.ConnectionManager(region)

results_topic = config.settings['results_topic']
state_domain = config.settings['states']['domain']
queue_name = config.settings['reactors']['alerting_reactor']['queue_name']

p = SQSReactor('alerting_reactor', conn_mgr, results_topic, [alerter,],
        state_domain, queue_name)

p.run()
