#!/usr/bin/env python

__doc__ = """CLI tool to report on reactor suppression filters."""

import boto.sdb
from nymms.suppress.cli import SuppressCommandArgs
import time
from nymms.utils import cli


args = SuppressCommandArgs()
args.add_argument('-t', '--time', dest='time',
        help='YYYMMDDHHMMSS or -XXX[smhd] time', default='0')
args.add_argument('-f', '--format', dest='format',
        help='Output format', choices=('csv', 'pretty'), default='pretty')
args.add_argument('-a', '--all', dest='show_all', action='store_true',
        help='Show all matching suppression filters, even inactive ones')

values = args.parse_args()
logger = cli.setup_logging(values.verbose)

from nymms.suppress.sdb_suppress import SDBSuppressFilterBackend
args.load_config()

expire = args.parse_time(values.time)
expire_time = time.gmtime(expire)
logger.debug("Searching for suppression filters active for %s",
        time.strftime("%Y-%m-%d %H:%M:%S", expire_time))

conn = boto.sdb.connect_to_region(args.region)

suppress = SDBSuppressFilterBackend(conn, args.domain)
filters = suppress.get_suppressions(expire, not values.show_all)
if values.format == 'csv':
    print "regex,created_at,expires,userid,ipaddr,comment,rowkey,active"

for item in filters:
    if item.expires < args.now() and not values.show_all:
        continue

    expires = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(item.expires))
    created_at = time.strftime("%Y-%m-%d %H:%M:%S",
            time.gmtime(item.created_at))
    if values.format == 'pretty':
        print "regex: '%s'\n\tcreated at: %s (%d)\t\texpires: %s (%d)" % (
            item.regex, created_at, item.created_at, expires, item.expires)
        print "\tcreated by: %s\tipaddr: %s\n\tcomment: %s" % (
            item.userid, item.ipaddr, item.comment)
        if (item.active == 'True') and int(item.expires) >= args.now():
            print "\trowkey: %s\t\tactive: %s\n" % (item.rowkey, item.active)
        elif (item.active == 'True'):
            print "\trowkey: %s\t\tactive: False\n" % (item.rowkey)
        else:
            print "\trowkey: %s\t\tactive: deactivated (%s)\n" % (item.rowkey,
                    item.active)

    elif values.format == 'csv':
        print "%s,%d,%d,%s,%s,%s,%s,%s" % (item.regex, item.created_at,
                item.expires, item.userid, item.ipaddr, item.comment,
                item.rowkey, item.active)
