#!/usr/bin/env python

"""CLI tool for marking reactor suppression as inactive"""

from nymms.utils import cli


parser = cli.NymmsCommandArgs(__doc__)
parser.add_argument('-k', '--key', dest='rowkey',
                    help='rowkey of suppression filter to deactivate')
parser.add_argument('--deactivate-all', dest='all_filters',
                    help='Deactivate all the suppression filters',
                    action='store_true')

args = parser.parse_args()
logger = cli.setup_logging(args.verbose)

from nymms.suppress.sdb_suppress import SDBSuppressionManager
from nymms.config import config
config.load_config(args.config)

region = config.settings['region']
cache_timeout = config.settings['suppress']['cache_timeout']
domain = config.settings['suppress']['domain']

suppress = SDBSuppressionManager(region, cache_timeout, domain)

if args.all_filters:
    suppress.deactivate_all_suppressions()
    print "Deactivated all active suppression filters"
elif args.rowkey:
    print "Deactivating %s" % (args.rowkey,)
    if not suppress.deactivate_suppression(args.rowkey):
        print "    ! Key %s not found." % (args.rowkey)
else:
    print "Please provide a --key or --deactivate-all"
    exit(-1)
