#!/usr/bin/env python

"""CLI tool for marking reactor suppression as inactive"""

import boto.sdb
from nymms.suppress.cli import SuppressCommandArgs
from nymms.utils.aws_helper import ConnectionManager
from nymms.utils import cli
import argparse
import time
import logging
import sys


args = SuppressCommandArgs(__doc__)
args.add_argument('-k', '--key', dest='rowkey',
        help='rowkey of suppression filter to deactivate')
args.add_argument('--deactivate-all', dest='all_filters',
        help='Deactivate all the suppression filters', action='store_true')

values = args.parse_args()
logger = cli.setup_logging(values.verbose)

from nymms.suppress.sdb_suppress import SDBSuppressFilterBackend
args.load_config()

aws = ConnectionManager(region=args.region)
suppress = SDBSuppressFilterBackend(aws.sdb, args.domain)

if values.all_filters:
    suppress.deactivate_all_suppressions()
    print "Deactivated all active suppression filters"
elif values.rowkey:
    print "Deactivating %s" % (values.rowkey,)
    suppress.deactivate_suppression(values.rowkey)
else:
    print "Please provide a --key or --deactivate-all-filters"
    exit(-1)
