#!/usr/bin/env python

from nymms.utils import aws_helper, cli

parser = cli.NymmsDaemonCommand()
args = parser.parse_args()

cli.setup_logging(args.verbose)

from nymms.config import config
from nymms.reactor.aws_reactor import AWSReactor

config.load_config(args.config)

region = config.settings['queue_region']
conn_mgr = aws_helper.ConnectionManager(region)

results_topic = config.settings['results_topic']
state_domain = config.settings['state_domain']
queue_name = config.settings['reactor']['queue_name']
handler_config_path = config.settings['reactor']['handler_config_path']
wait_time = config.settings['reactor']['queue_wait_time']
visibility_timeout = config.settings['reactor']['visibility_timeout']

daemon = AWSReactor(conn_mgr, results_topic, state_domain, queue_name)

daemon.run(handler_config_path,
           wait_time=wait_time,
           visibility_timeout=visibility_timeout)
