#!/usr/bin/env python

"""CLI tool for marking reactor suppression as inactive"""

import boto.sdb
from nymms.utils.aws_helper import ConnectionManager
from nymms.utils import cli
import time
import logging
import sys


parser = cli.NymmsCommandArgs(__doc__)
parser.add_argument('-k', '--key', dest='rowkey',
        help='rowkey of suppression filter to deactivate')
parser.add_argument('--deactivate-all', dest='all_filters',
        help='Deactivate all the suppression filters', action='store_true')

args = parser.parse_args()
logger = cli.setup_logging(args.verbose)

from nymms.suppress.sdb_suppress import SDBSuppressFilterBackend
from nymms.config import config
config.load_config(args.config)

aws = ConnectionManager(region=config.settings['region'])
suppress = SDBSuppressFilterBackend(aws.sdb,
        config.settings['suppress']['cache_timeout'],
        config.settings['suppress']['domain'])

if args.all_filters:
    suppress.deactivate_all_suppressions()
    print "Deactivated all active suppression filters"
elif args.rowkey:
    print "Deactivating %s" % (args.rowkey,)
    suppress.deactivate_suppression(args.rowkey)
else:
    print "Please provide a --key or --deactivate-all-filters"
    exit(-1)
