#!/usr/bin/env python

import os
from boto import sqs
from boto import sns

from nymms.utils import logutil, aws_helper

logger = logutil.setup_root_logger(stdout=logutil.INFO,
        filename='/tmp/nymms-probe-%d.log' % (os.getpid()),
        file_level=logutil.DEBUG)
logutil.quiet_boto_logging()

from nymms.config import config
config.load_config('~/git/nymms/conf/config.yaml')

from nymms.resources import (MonitoringGroup, Monitor, Command, Node,
        load_resources)
from nymms.probe.sqs_probe import SQSProbe

resource_version = load_resources(config.settings['resources'])
region = config.settings['queue_region']
conn_mgr = aws_helper.ConnectionManager(region)

tasks_queue = config.settings['tasks']['name']
results_topic = config.settings['results_topic']
state_domain = config.settings['states']['domain']

p = SQSProbe(conn_mgr, tasks_queue, results_topic, state_domain)
p.run()
