#!/usr/bin/env python

import os
from boto import sqs
from boto import sns

from nymms.utils import logutil

logger = logutil.setup_root_logger(stdout=logutil.INFO,
        filename='/tmp/nymms-probe-%d.log' % (os.getpid()),
        file_level=logutil.DEBUG)
logutil.quiet_boto_logging()

from nymms.config import config
config.load_config('~/git/nymms/conf/config.yaml')

from nymms.resources import (MonitoringGroup, Monitor, Command, Node,
        load_resources)
from nymms.probe.sqsprobe import SQSProbe

resource_version = load_resources(config.settings['resources'])
sqs_conn = sqs.connect_to_region(config.settings['queue_region'])
sns_conn = sns.connect_to_region(config.settings['queue_region'])
p = SQSProbe(sqs_conn, sns_conn, config.settings['tasks']['name'],
        config.settings['results_topic'])
p.run()
