#!/usr/bin/env python

import os
from boto import sqs
from boto import sns

from nymms.utils import logutil

logger = logutil.setup_root_logger(stdout=logutil.INFO,
        filename='/tmp/nymms-reactor-%d.log' % (os.getpid()),
        file_level=logutil.DEBUG)
logutil.quiet_boto_logging()

from nymms.config import config
config.load_config('~/git/nymms/conf/config.yaml')

from nymms.reactor.sqs_reactor import SQSReactor
from nymms.alerter.ses_alerter import SESAlerter
from nymms.alerter.log_alerter import LogAlerter

alerter = SESAlerter(config.settings['queue_region'])
#alerter = LogAlerter()

sqs_conn = sqs.connect_to_region(config.settings['queue_region'])
sns_conn = sns.connect_to_region(config.settings['queue_region'])
p = SQSReactor('alerting_reactor', sqs_conn, sns_conn,
        config.settings['results_topic'],
        [alerter,],
        config.settings['reactors']['alerting_reactor']['queue_name'])
p.run()
