#!/usr/bin/env python

from nymms.utils import aws_helper, cli

parser = cli.NymmsDaemonCommand()
args = parser.parse_args()

cli.setup_logging(args.verbose)

from nymms.config import config
from nymms.resources import load_resources
from nymms.scheduler.sqs_scheduler import SQSScheduler, YamlNodeBackend

config.load_config(args.config)

resource_version = load_resources(config.settings['resources'])

be = YamlNodeBackend(config.settings['nodes'])
conn_mgr = aws_helper.ConnectionManager(config.settings['queue_region'])

s = SQSScheduler(conn_mgr, config.settings['tasks']['name'], be)
s.run()
