#!/usr/bin/env python

import os

from nymms.utils import logutil
from nymms.utils import aws_helper

logger = logutil.setup_root_logger(stdout=logutil.INFO,
        filename='/tmp/nymms-scheduler.log', file_level=logutil.DEBUG)
logutil.quiet_boto_logging()

from nymms.config import config
config.load_config('~/git/nymms/conf/config.yaml')

from nymms.resources import (MonitoringGroup, Monitor, Command, Node,
        load_resources)
from nymms.scheduler.sqs_scheduler import SQSScheduler, YamlNodeBackend

resource_version = load_resources(config.settings['resources'])

be = YamlNodeBackend(config.settings['nodes'])

conn_mgr = aws_helper.ConnectionManager(config.settings['queue_region'])

s = SQSScheduler(conn_mgr, config.settings['tasks']['name'], be)
s.run()
