#!/usr/bin/env python

from nanomon.utils import logutil

from nanomon import scheduler
from nanomon.queue.backends.sns_sqs import SNSTopic, SQSQueue
from boto import sns
from boto import sqs

logger = logutil.setup_logging(tag_name='worker', verbose=True, stdout=True,
        syslog=False)
logutil.quiet_boto_logging()

sns_conn = sns.connect_to_region('us-west-2')
sqs_conn = sqs.connect_to_region('us-west-2')

topic = SNSTopic(sns_conn, 'tasks')
queue = SQSQueue(sqs_conn, 'tasks')

worker = scheduler.TaskWorker(topic, queue)

worker.run(max_sleep=10)
